extra_css:
  - stylesheets/extra.css
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/VectorInstitute/aieng-template-mvp
markdown_extensions:
  - attr_list
  - admonition
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.details
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.arithmatex:
      generic: true
  - toc:
      permalink: true
nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Backend Development: backend-development.md
  - Frontend Development: frontend-development.md
  - Docker and Deployment: docker-deployment.md
  - Template UI: template-preview.md
plugins:
  - search
  - include-markdown
repo_url: https://github.com/VectorInstitute/aieng-template-mvp
repo_name: VectorInstitute/aieng-template-mvp
site_name: AI Engineering MVP Template
theme:
  custom_dir: docs/overrides
  favicon: assets/favicon-48x48.svg
  features:
    - content.code.annotate
    - content.code.copy
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.tabs
    - navigation.top
    - search.suggest
    - search.highlight
    - toc.follow
  icon:
    repo: fontawesome/brands/github
  logo: assets/vector-logo.svg
  logo_footer: assets/vector-logo.svg
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: vector
      accent: vector-teal
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: vector-teal
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
